apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  labels:
    app.kubernetes.io/name: cluster-issuer
    app.kubernetes.io/instance: cluster-issuer
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: raw-0.2.5
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: andreas.lindhe@combitech.com
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - http01:
        ingress:
          class: nginx
